HOST         = 
DB           = 
USER         = 
PORT         = 
PASSWORD     = 
URI          = postgresql://
CREATE_FILE  = sql_files/create_db.sql
UPDATE_FILE  = sql_files/update_db.sql
CLEAR_FILE   = sql_files/clear_mentions_db.sql
INSERT_FILE  = sql_files/insert_db.sql
